"C:\Program Files\Bullzip\PDF Printer\API\EXE\config.exe" /S Output "%1"
"C:\Program Files\Bullzip\PDF Printer\API\EXE\config.exe" /S ConfirmOverwrite "No"
"C:\Program Files\Bullzip\PDF Printer\API\EXE\config.exe" /S ConfirmNewFolder "No"
"C:\Program Files\Bullzip\PDF Printer\API\EXE\config.exe" /S ShowSettings "Never"
"C:\Program Files\Bullzip\PDF Printer\API\EXE\config.exe" /S ShowSaveAS "Never"
"C:\Program Files\Bullzip\PDF Printer\API\EXE\config.exe" /S ShowPDF "Never"
"C:\Program Files\Bullzip\PDF Printer\API\EXE\config.exe" /S OpenFolder "No"
"C:\Program Files\Bullzip\PDF Printer\API\EXE\config.exe" /S ShowProgress "No"
"C:\Program Files\Bullzip\PDF Printer\API\EXE\config.exe" /S ShowProgressFinished "No"
"C:\Program Files\Bullzip\PDF Printer\API\EXE\config.exe" /S Author "Analytics for Everyone"
"C:\Program Files\Bullzip\PDF Printer\API\EXE\config.exe" /S Title "Your sales forecast report powered by A4E"
REM "C:\Program Files\Bullzip\PDF Printer\API\EXE\config.exe" /S Creator "Analytics for Everyone"
REM "C:\Program Files\Bullzip\PDF Printer\API\EXE\config.exe" /S Producer "Analytics for Everyone"
"C:\Program Files\Bullzip\PDF Printer\API\EXE\config.exe" /S Target "default"
"C:\Program Files\Bullzip\PDF Printer\API\EXE\config.exe" /S Zoom "100"
"C:\Program Files\Bullzip\PDF Printer\API\EXE\config.exe" /S RunOnSuccess "%USERPROFILE%\work\printing\onendprint.bat success %1 %2 %3 %4"
"C:\Program Files\Bullzip\PDF Printer\API\EXE\config.exe" /S RunOnSuccessDir "%USERPROFILE%\work\printing\"
"C:\Program Files\Bullzip\PDF Printer\API\EXE\config.exe" /S RunOnError "%USERPROFILE%\work\printing\onendprint.bat error %1 %2 %3 %4"
"C:\Program Files\Bullzip\PDF Printer\API\EXE\config.exe" /S RunOnErrorDir "%USERPROFILE%\work\printing\"
"C:\Program Files\Bullzip\PDF Printer\API\EXE\config.exe" /S SuppressErrors "yes"
